### ISSUE TITLE
subdomain redirecting

### ISSUE THREAD

**Issue by greentheo** [opencpu/opencpu#134]
I recently asked this question on stackoverflow:  http://stackoverflow.com/questions/28598283/configuring-opencpu-with-a-subdomain 

But am completely lost on what and where I would add in a subdomain to nginx and how it would work in with the existing ocpu configurations.

This is as close as I could get:  http://askubuntu.com/questions/500638/nginx-reverse-proxy-and-subdomains

Is there any chance you can add perhaps a commented out block to the ocpu server/cache configurations that if uncommented and modified with the correct subdomain/domain would redirect? 

myapp.domain.com -> domain.com/ocpu/library/myapp/www

**Comment by jeroenooms** [comment]
This is really more of a web admin question. It's also not completely clear what you have in mind. You say:

> myapp.domain.com -> domain.com/ocpu/library/myapp/www

However in order for the client application to interact with the opencpu server, it needs to be able to reach at least `/ocpu/library/myapp/R/` and `/ocpu/tmp/` as well. So if you only expose the `/www` dir, your app likely won't work.

Maybe you are making it too complicated. If you just want your app to be reachable at myapp.domain.com because it is easier to remember for people, one simple trick would be to create an `index.html` page in your `myapp.domain.com` site containing only an iframe:

```html
<iframe src="http://domain.com/ocpu/library/myapp/www"></iframe>
```

And then with some css you can make the iframe take 100% of the width and height of the page and remove the border, making it look like the original page with no server side changes required. I put an example [here](https://gist.github.com/jeroenooms/d2707b091217847d315c).

Another approach might be to host a copy (or symlink) if your `/myapp/www` dir in your `myapp.domain.com` site and then use the `ocpu.seturl` to point it to the real location of the package. Look at any of the [jsfiddle](http://jsfiddle.net/user/opencpu/fiddles/) examples to see how `seturl` is used to call opencpu from another location.

**Comment by greentheo** [comment]
okay good references... i'll take a look at them and let you know if there's further questions.

I hadn't even thought of the need to keep the /ocpu/library/myapp/R and ocpu/tmp available.

I might be making it too complicated in the end and yes, just trying to make it easier to remember (and put on marketing/promotional materials).

**Comment by greentheo** [comment]
turns out that the main problem here was that I hadn't read the documentation fully enough to see that opencpu-cache was what was tripping my efforts to get the apache subdomain directing correctly.  

And in fact that you recommend running it on (or opencpu) on a different server.  

With opencpu-cache disabled nginx and apache are working more harmoniously together!

**Comment by jeroen** [comment]
Cleaning up old issues. Please open a new issue if this problem still exists in OpenCPU 2.0.
