### ISSUE TITLE
Session-less self-contained HTML output for RPC

### ISSUE THREAD

**Issue by mjmg** [opencpu/opencpu#278]
I'm only interested in the HTML output of a package such as from brew output or htmlwidget:::saveWidget self contained html output for embedding into iframes. 

Is it possible to have this without two calls with the session ID as a parameter in the second call to get the HTML output?

**Comment by jeroen** [comment]
How do you imagine this would look? The html widget consists of many files. The HTML is not the entire widget, it needs to load other files like `js`/`css`/ etc. So it's not possible to just give the entire widget in the response. The server needs to copy it somewhere so that the client can GET to the html and all resources.

**Comment by mjmg** [comment]
htmlwidget::saveWidget has a self-contained option with choice of whether to save the HTML as a single self-contained file (with external resources base64 encoded) or a file with external resources placed in an adjacent directory.
https://rdrr.io/cran/htmlwidgets/man/saveWidget.html

If I enable the self-contained option, I can have a single html file without external directory dependency.
```
require("ggplot2")
require("plotly")
require("widgetframe")

gg<-ggplot(midwest, aes(x=area, y=poptotal)) + geom_point()

ggp<-ggplotly(gg)

htmlwidgets::saveWidget(widgetframe::frameableWidget(ggp),'ggplotly_plot_selfcontained.html', selfcontained = TRUE)
```
The self-contained html generated contains all the necessary resources without external directories.

If I disable the self-contained option, a regular HTML file is generated with external resources.
```
require("ggplot2")
require("plotly")
require("widgetframe")

gg<-ggplot(midwest, aes(x=area, y=poptotal)) + geom_point()

ggp<-ggplotly(gg)

htmlwidgets::saveWidget(widgetframe::frameableWidget(ggp),'ggplotly_plot_notselfcontained.html', selfcontained = FALSE)

```

**Comment by jeroen** [comment]
OK well you could create a wrapper function that reads the html file and then returns the content:

```r
require("ggplot2")
require("plotly")
require("widgetframe")

gg<-ggplot(midwest, aes(x=area, y=poptotal)) + geom_point()

ggp<-ggplotly(gg)

htmlwidgets::saveWidget(widgetframe::frameableWidget(ggp),'ggplotly_plot_selfcontained.html', selfcontained = TRUE)
data <- readLines('ggplotly_plot_selfcontained.html')
return(list(text = paste(data, collapse = "\n")))
```

And then you can append `/json` to the function call as exemplified [in the documentation](https://www.opencpu.org/api.html#api-json) and you get the resulting html back as json text.

Alternatively you can do the same but read the html as a raw vector and use `/bin` instead of `/json` to get the result. So your function would be:

```r
myfun <- function(){
  gg<-ggplot(midwest, aes(x=area, y=poptotal)) + geom_point()
  ggp<-ggplotly(gg)
  htmlwidgets::saveWidget(widgetframe::frameableWidget(ggp),'ggplotly_plot_selfcontained.html', selfcontained = TRUE)
  rawhtml <- readBin('ggplotly_plot_selfcontained.html', raw(), file.info('ggplotly_plot_selfcontained.html')$size)
  return(rawhtml)
```

And then you call that using eg

```
curl https://cloud.opencpu.org/ocpu/pkg/R/myfun/bin -d << your args >>
```

And that should return the raw html data.

**Comment by mjmg** [comment]
Got it, thanks. Closing.
