### ISSUE TITLE
killing orphans :)

### ISSUE THREAD

**Issue by jeroen** [opencpu/opencpu#53]
run killorphans script as cron job?

**Comment by rubenarslan** [comment]
1. A belated happy birthday :-) 
2. Can I ask something about this script? On my VMs it doesn't seem to ever finish (I attempted to run it manually because an inactive machine went from 0.5GB memory used to 19GB used over night and anyway the memory usage doesn't seem proper). How could I debug this?

**Comment by jeroen** [comment]
This should no longer be needed with the new `sys` package.
